spring.main.web-application-type=none
spring.application.ui.title=Elephant

spring.jpa.database-platform=com.example.demo.ide.Infrastructure.Repositories.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:sqlite:memory:myDb?cache=shared
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.datasource.username=elephant
spring.datasource.password=secret

spring.jpa.show-sql=true
